import mongoose from 'mongoose';
import db from '$lib/db.js';
const LandingPageSchema = new mongoose.Schema(
	{
		lang: String,
		lpPerma: String,
		lpName: String,
		lpTitle: String,
		treatment: {
			type: mongoose.Schema.Types.ObjectId,
			required: false,
			ref: 'treatment'
		},
		treatmentGroup: {
			type: mongoose.Schema.Types.ObjectId,
			required: false,
			ref: 'treatmentGroup'
		},

		infoSpot: String,
		infoText1: String,
		infoText2: String,
		infoImage: String,
		infoVideoLink: String,
		infoVideoImage: String,

		slider1Name: String,
		slider1Image: String,
		slider1MobileImage: String,
		slider1Text: String,
		slider1Button: String,
		slider1Whatsapp: Boolean,
		slider1ButtonColor: String,
		slider1ButtonTextColor: String,
		slider1TextColor: String,
		slider1Direction: String,
		slider2Name: String,
		slider2Image: String,
		slider2MobileImage: String,
		slider2Text: String,
		slider2Button: String,
		slider2Whatsapp: Boolean,
		slider2ButtonColor: String,
		slider2ButtonTextColor: String,
		slider2TextColor: String,
		slider2Direction: String,
		slider3Name: String,
		slider3Image: String,
		slider3MobileImage: String,
		slider3Text: String,
		slider3Button: String,
		slider3ButtonTextColor: String,
		slider3TextColor: String,
		slider3Whatsapp: Boolean,
		slider3ButtonColor: String,
		slider3Direction: String,

		infoSpot: String,
		infoText1: String,
		infoText2: String,
		infoImage: String,

		formSlogan1: String,
		formSlogan2: String,
		formSlogan3: String,
		formButton: String,
		formSpot: String,
		formHeader: String,
		formWhatsappText: String,

		featuresSpot: String,
		featuresHeader: String,
		features1Image: String,
		features1Header: String,
		features1Text: String,
		features2Image: String,
		features2Header: String,
		features2Text: String,
		isFaq: Boolean,
		faq1q: String,
		faq1a: String,
		faq2q: String,
		faq2a: String,
		faq3q: String,
		faq3a: String,
		faq4q: String,
		faq4a: String,
		faq5q: String,
		faq5a: String,
		isTab: Boolean,
		tab1Header: String,
		tab1Text1: String,
		tab1Text2: String,
		tab1Image: String,
		tab2Header: String,
		tab2Text1: String,
		tab2Text2: String,
		tab2Image: String,
		tab3Header: String,
		tab3Text1: String,
		tab3Text2: String,
		tab3Image: String,
		tab4Header: String,
		tab4Text1: String,
		tab4Text2: String,
		tab4Image: String,

		testimonialSpot: String,
		testimonialHeader: String,
		videoSpot: String,
		videoHeader: String,
		link1: String,
		link1Perma: String,
		link2: String,
		link2Perma: String,
		link3: String,
		link3Perma: String,
		link4: String,
		link4Perma: String,

		companyShortDesc: String,
		address1: String,
		address2: String,
		email: String,
		phone: String,
		whatsapp: String,
		wpMessage: String,

		infoWithSliderImage1: String,
		infoWithSliderImage2: String,
		infoWithSliderImage3: String,
		infoWithSliderSpot: String,
		infoWithSliderHeader: String,
		infoWithSliderText: String,
		infoWithVideoSpot: String,
		infoWithVideoHeader: String,
		infoWithVideoVideoImage: String,
		infoWithVideoVideoName: String,
		infoWithVideoVideoLink: String,
		infoWithVideoText: String,
		beforeAfterHeader: String,
		beforeAfterSpot: String,
		firstBefore: String,
		firstAfter: String,
		secondBefore: String,
		secondAfter: String,
		thirdBefore: String,
		thirdAfter: String
	},
	{ timestamps: true }
);

export const LandingPage = mongoose.model('landingPage', LandingPageSchema);

export default { LandingPage };
